swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Users
  license:
    name: MIT
host: users.swagger.io
basePath: /v1
schemes:
  - http
produces:
  - application/json
paths:
  /:
    get:
      summary: Index page
      operationId: index
      consumes: text/plain
      produces: application/json
      tags:
        - index
      responses:
        default:
          description: index page data
          schema:
            $ref: "#/definitions/IndexPage"

  /users/{id}:
    get:
      summary: Info for a specific user
      operationId: getUserById
      consumes: text/plain
      produces: application/json
      tags:
        - users
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the user to retrieve
          type: integer
          format: int64
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/User'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  IndexPage:
    properties:
      name:
        type: string
  User:
    required:
      - id
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string